src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: BookingRepository::class)]
#[ORM\HasLifecycleCallbacks()]
class Booking
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'bookings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $booker = null;

    #[ORM\ManyToOne(inversedBy: 'bookings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Ad $ad = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\Type("DateTimeInterface", message: "La date d'arrivée doit être au bon format")]
    #[Assert\GreaterThan('today', message: 'La date d\'arrivée doit être ultérieure à la date d\'aujourd\'hui', groups: ['front'])]
    private ?\DateTimeInterface $startDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\Type("DateTimeInterface",message: "La date de départ doit être au bon format")]
    #[Assert\GreaterThan(propertyPath: "startDate", message: "La date de départ doit être plus éloignée que la date d'aujourd'hui")]
    private ?\DateTimeInterface $endDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column]
    private ?float $amount = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $comment = null;

    #[ORM\PrePersist()]
    #[ORM\PreUpdate()]
    public function prePersist() {
        if(empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }

        if(empty($this->amount)) {
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    public function isBookableDates()
    {
        $notAvailableDays = $this->ad->getNotAvailableDays();

        $bookingDays = $this->getDays();

        $days = array_map(function ($days) {
            return $days->format('Y-m-d');
        }, $bookingDays);

        $notAvailable = array_map(function ($days) {
            return $days->format('Y-m-d');
        }, $notAvailableDays);

        foreach ($days as $day) {
            if(array_search($day, $notAvailable) !== false) {
                return false;
            }
        }

        return true;
    }

    public function getDays()
    {
        $resultat = range($this->startDate->getTimestamp(), $this->endDate->getTimestamp(), 24*60*60);

        $days = array_map(function ($dayTimestamp) {
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $resultat);

        return $days;
    }

    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity(fields: ["email"], message: "Une autre utilisateur possède déjà ce login, merci de le modifier")]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Votre prénom doit être renseigné")]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Votre nom doit être renseigné")]
    private ?string $lastName = null;

    #[ORM\Column(length: 255)]
    #[Assert\Email(message: "Veuillez renseigner un email valide")]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Url(message: "Veuillez renseigner une url valide")]
    private ?string $picture = null;

    #[ORM\Column(length: 255)]
    private ?string $hash = null;

    #[Assert\EqualTo(propertyPath: "hash", message: "Vous n'avez pas confirmé votre mot de passe")]
    public $passwordConfirm;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min: 10,
        minMessage: "Votre introduction ne peut pas faire moins de 10 caractères")]
    private ?string $introduction = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\Length(min: 100,
        minMessage: "Votre description ne peut pas faire moins de 100 caractères")]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Ad::class)]
    private Collection $ads;

    #[ORM\ManyToMany(targetEntity: Role::class, mappedBy: 'users')]
    private Collection $userRoles;

    #[ORM\OneToMany(mappedBy: 'booker', targetEntity: Booking::class)]
    private Collection $bookings;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getFullName() {
        return "{$this->firstName} {$this->lastName}";
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function initializeSlug() {
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName.' '.$this->lastName);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, Ad>
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getRoles(): array
    {
        $roles = $this->userRoles->toArray();

        $roles = $this->userRoles->map(function ($role){
            return $role->getTitle();
        })->toArray();

        $roles[] = 'ROLE_USER';

        return $roles;
    }

    public function getUserIdentifier(): string
    {
        return $this->email;
    }

    public function getPassword(): ?string
    {
        return $this->hash;
    }

    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @return Collection<int, Role>
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->removeElement($userRole)) {
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Booking>
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\DataTransformer\FrenchToDateTimeTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookingType extends ApplicationType
{
    private $transformer;
    public function __construct(FrenchToDateTimeTransformer $transformer)
    {
        $this->transformer = $transformer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('startDate', TextType::class, $this->getConfiguration('Date d\'arrivée', 'La Date à laquelle vous comptez arriver'))
            ->add('endDate', TextType::class, $this->getConfiguration('Date de départ', 'La date à laquelle vous quittez les lieux'))
        ->add('comment', TextareaType::class, $this->getConfiguration(false, "Si vous avez un commentaire, n'hésitez pas à nous en faire part !", ['required' => false]));
        ;

        $builder->get('startDate')->addModelTransformer($this->transformer);
        $builder->get('endDate')->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
            'validation_groups' => [
                'Default',
                'front'
            ]
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BookingController extends AbstractController
{
    #[Route('/ads/{slug}/book', name: 'booking_create')]
    #[IsGranted("ROLE_USER")]
    public function index(Ad $ad, Request $request, EntityManagerInterface $manager): Response
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();
            $booking->setBooker($user);
            $booking->setAd($ad);

            if(!$booking->isBookableDates()) {
                $this->addFlash(
                    'warning',
                    "Les dates que vous avez choisi ne peuvent être réservées : elles sont déjà prises");
            } else {
                $manager->persist($booking);
                $manager->flush();

                return $this->redirectToRoute('booking_show', ['id' => $booking->getId(), 'withAlert' => true]);
            }
        }

        return $this->render('booking/book.html.twig', [
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }

    #[Route('/booking/{id}', name: 'booking_show')]
    public function show(Booking $booking, Request $request, EntityManagerInterface $manager)
    {

        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {

            $comment->setAuthor($this->getUser())
                ->setAd($booking->getAd());

            $manager->persist($comment);
            $manager->flush();


            $this->addFlash('success', 'Votre commentaire a été bien prise en compte');

            return $this->redirectToRoute("booking_show", ['id' => $booking->getId()]);
        }

        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
            'form' => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation de l'annonce : {{ ad.title }}{% endblock %}



{% block body %}
<div class="container">
    <h1>Réverver pour l'annonce : {{ ad.title }}</h1>
    <p>Vous êtes sur le point de réserver le bien de <strong>{{ ad.author.fullName }}</strong>, dites nous tous on s'occupe du reste !</p>

    {{ form_start(form) }}
    <div class="alert-light">
        <h2>Commencez par nous dire quelles sont les dates qui vous intéressent !</h2>
        <div class="row">
            <div class="col">{{ form_row(form.startDate) }}</div>
            <div class="col">{{ form_row(form.endDate) }}</div>
        </div>

        <h4>Montant du séjour : <span id="amount">...</span> &euro;</h4>
        <span id="days">0</span> nuit(s) à {{ ad.price }} /nuit
        <h2>Vous avez un commentaire ?</h2>

        {{ form_row(form.comment) }}
    </div>


    <h2>Vous avez terminez ?</h2>
    <p>Vacances de rêve ? Hébergement pour le boulot ? Peu importe, on est avec vous !</p>

    <input type="submit" class="btn btn-success" value="Je réserve !">

    {{ form_end(form) }}
</div>
{% endblock %}

{% block javascripts %}

    {{ parent() }}

    <script src="/jquery.js"></script>
    <script>



        $(document).ready(function () {
            $('#booking_startDate, #booking_endDate').datepicker({
                format: 'dd/mm/yyyy',
                language: 'fr',
                forceParse: false,
                todayHighlight : true,
                datesDisabled : [
                    {% for day in ad.notAvailableDays %}
                    "{{ day.format('d/m/Y') }}",
                    {% endfor %}
                ],
                startDate: new Date()
            });

            $('#booking_startDate, #booking_endDate').on('change', calculateAmount);
        });

        function calculateAmount() {
            const endDate = new Date($("#booking_endDate").val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3,$2,$1'));
            const startDate = new Date($("#booking_startDate").val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3,$2,$1'));

            if(startDate && endDate && startDate < endDate) {
                const DATE_TIME = 24 * 60 * 60 * 1000;

                const interval = endDate.getTime() - startDate.getTime();
                const days = interval / DATE_TIME;
                const amount = days * {{ ad.price }};

                $('#days').text(days);
                $('#amount').text(amount.toLocaleString('fr-FR'));
            }
        }
    </script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation N° : {{ booking.id }}{% endblock %}

{% block body %}

    {% set ad = booking.ad %}
    {% set author = ad.author %}
    <div class="container">
        {% if app.request.query.get('withAlert') %}
            <div class="alert alert-success">
                <h4 class="alert-heading">
                    <p>Votre réservation auprès de
                        <strong><a href="{{ path('user_show', {'slug' : author.slug}) }}">{{ author.fullName }}</a></strong>
                        pour
                        l'annonce
                        <strong>
                            <a href="{{ path('ads_show', {'slug' : ad.slug}) }}">{{ ad.title }}</a>
                        </strong>
                        a bien été prise en compte !
                    </p>
                </h4>
            </div>
        {% endif %}

        <h1>Révervation N° : {{ booking.id }}</h1>

        <div class="row">
            <div class="col-md-6">
                <div class="alert-light">
                    <h2>Détails</h2>
                    <dl class="row">
                        <dt class="col-md-4">Numéro</dt>
                        <dd class="col-md-8">{{ booking.id }}</dd>
                        <dt class="col-md-4">Date d'arrivée</dt>
                        <dd class="col-md-8">{{ booking.startDate | date('d/m/Y') }}</dd>
                        <dt class="col-md-4">Date de départ</dt>
                        <dd class="col-md-8">{{ booking.endDate | date('d/m/Y') }}</dd>
                        <dt class="col-md-4">Nombre de nuits</dt>
                        <dd class="col-md-8">{{ booking.duration }}</dd>
                        <dt class="col-md-4">Montant Total</dt>
                        <dd class="col-md-8">{{ booking.amount }} &euro;</dd>
                        <dt class="col-md-4">Commentaire</dt>
                        <dd class="col-md-8">{{ booking.comment | default('Aucun commentaire') }}</dd>
                    </dl>
                    <hr>
                    <h2 class="alert-heading">Votre hôte</h2>

                    <div class="row">
                        <div class="col-3">
                            <img src="{{ author.picture }}" class="avatar avatar-medium"
                                 alt="Avatar de {{ author.fullName }}">
                        </div>
                        <div class="col-9">
                            <h4>
                                <a href="{{ path('user_show', {'slug': author.slug}) }}">
                                    {{ author.fullName }}
                                </a>
                            </h4>
                            <span class="badge bg-primary">{{ author.ads | length }} annonces</span>
                        </div>
                    </div>
                    {{ author.description | raw }}

                    <a class="btn btn-primary" href="{{ path('user_show', {'slug': author.slug}) }}">Plus d'infos
                        sur {{ author.firstName }}</a>
                </div>
                <div class="alert-light mt-3" id="comment">
                    <h2 class="alert-heading">Votre avis compte !</h2>
                    {% if date() > date(booking.endDate) %}

                        {% set comment = booking.ad.commentFromAuthor(app.user) %}
                        {% if comment is not null %}
                            <blockquote>
                                {{ comment.contenu }}
                            </blockquote>
                            <strong>Note
                                : {% include 'partials/rating.html.twig' with {'rating' : comment.rating} %}</strong>
                        {% else %}
                            {{ form_start(form) }}
                            {{ form_widget(form) }}
                            <input type="submit" class="btn btn-success" value="Confirmer">
                            {{ form_end(form) }}
                        {% endif %}
                    {% else %}
                        <p>Vous ne pourrez pas noter cette annonce tant que votre voyage ne sera pas complet !</p>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-6">
                <div class="alert-light">
                    <h2 class="alert-heading">Votre hébergement</h2>
                    <h4>
                        <a href="{{ path('ads_show', {'slug': ad.slug}) }}">{{ ad.title }}</a>
                    </h4>
                    <img src="{{ ad.coverImage }}" alt="Image de {{ ad.title }}" class="img-fluid">
                    {{ ad.contenu | raw }}

                    <a class="btn btn-primary" href="{{ path('ads_show', {'slug': ad.slug}) }}">Plus d'informations</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}